import os
import streamlit as st

# BASE DIR
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
trainer_path = os.path.join(BASE_DIR, "trainer.yml")

# Check if file exists
if not os.path.exists(trainer_path):
    st.error("trainer.yml file GitHub var sapdat nahiye. Krupaya push kara.")
    st.stop()

# Load model
recognizer.read(trainer_path)
